export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE"
export const DELETE_FLASH_MESSAGE = "DELETE_FLASH_MESSAGE"

export const SET_CURRENT_USER = "SET_CURRENT_USER"

export const SET_CONFIG = "SET_CONFIG"

export const SET_GLOBAL_CONFIG="SET_GLOBAL_CONFIG"